version: "3.9"
services:
  web:
    build: .
    command: bash -c "bundle exec rails db:create db:migrate && tail -f /dev/null"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
